"""
Canonical exercise registry.

Each entry in CANONICAL_EXERCISES is keyed by canonical_name (snake_case).
It defines the authoritative display name, all known aliases, exercise type,
muscle group, rep range, and default progression rate.

Use normalize_exercise_name() to map any user-supplied name to a canonical key.
Use get_exercise_metadata() to retrieve the full metadata dict.
"""

from typing import Optional

# ---------------------------------------------------------------------------
# Registry — single source of truth for all canonical exercises
# ---------------------------------------------------------------------------

CANONICAL_EXERCISES: dict[str, dict] = {
    # ── Chest ────────────────────────────────────────────────────────────────
    "bench_press": {
        "display_name": "Bench Press",
        "exercise_type": "compound",
        "muscle_group": "Chest",
        "equipment": "Barbell",
        "rep_range_min": 5,
        "rep_range_max": 12,
        "progression_rate": 0.025,
        "aliases": [
            "bench press", "barbell bench press", "bb bench", "bb bench press",
            "flat bench press", "flat bench", "bench",
        ],
    },
    "incline_bench_press": {
        "display_name": "Incline Bench Press",
        "exercise_type": "compound",
        "muscle_group": "Chest",
        "equipment": "Barbell",
        "rep_range_min": 6,
        "rep_range_max": 12,
        "progression_rate": 0.025,
        "aliases": [
            "incline bench press", "incline barbell bench press",
            "incline bench", "incline bb bench",
        ],
    },
    "decline_bench_press": {
        "display_name": "Decline Bench Press",
        "exercise_type": "compound",
        "muscle_group": "Chest",
        "equipment": "Barbell",
        "rep_range_min": 6,
        "rep_range_max": 12,
        "progression_rate": 0.025,
        "aliases": [
            "decline bench press", "decline barbell bench press",
            "decline bench",
        ],
    },
    "dumbbell_bench_press": {
        "display_name": "Dumbbell Bench Press",
        "exercise_type": "compound",
        "muscle_group": "Chest",
        "equipment": "Dumbbell",
        "rep_range_min": 8,
        "rep_range_max": 15,
        "progression_rate": 0.025,
        "aliases": [
            "dumbbell bench press", "db bench press", "db bench",
            "dumbbell flat bench",
        ],
    },
    "incline_dumbbell_press": {
        "display_name": "Incline Dumbbell Press",
        "exercise_type": "compound",
        "muscle_group": "Chest",
        "equipment": "Dumbbell",
        "rep_range_min": 8,
        "rep_range_max": 15,
        "progression_rate": 0.025,
        "aliases": [
            "incline dumbbell bench press", "incline dumbbell press",
            "incline db press", "incline db bench",
        ],
    },
    "decline_dumbbell_press": {
        "display_name": "Decline Dumbbell Press",
        "exercise_type": "compound",
        "muscle_group": "Chest",
        "equipment": "Dumbbell",
        "rep_range_min": 8,
        "rep_range_max": 15,
        "progression_rate": 0.025,
        "aliases": [
            "decline dumbbell bench press", "decline dumbbell press",
            "decline db press",
        ],
    },
    "dumbbell_fly": {
        "display_name": "Dumbbell Fly",
        "exercise_type": "isolation",
        "muscle_group": "Chest",
        "equipment": "Dumbbell",
        "rep_range_min": 10,
        "rep_range_max": 15,
        "progression_rate": 0.015,
        "aliases": ["dumbbell fly", "db fly", "dumbbell flies", "db flies", "chest fly"],
    },
    "incline_dumbbell_fly": {
        "display_name": "Incline Dumbbell Fly",
        "exercise_type": "isolation",
        "muscle_group": "Chest",
        "equipment": "Dumbbell",
        "rep_range_min": 10,
        "rep_range_max": 15,
        "progression_rate": 0.015,
        "aliases": ["incline dumbbell fly", "incline db fly"],
    },
    "cable_chest_fly": {
        "display_name": "Cable Chest Fly",
        "exercise_type": "isolation",
        "muscle_group": "Chest",
        "equipment": "Cable",
        "rep_range_min": 10,
        "rep_range_max": 15,
        "progression_rate": 0.015,
        "aliases": ["cable chest fly", "cable fly", "cable crossover"],
    },
    "pec_deck": {
        "display_name": "Pec Deck",
        "exercise_type": "isolation",
        "muscle_group": "Chest",
        "equipment": "Machine",
        "rep_range_min": 10,
        "rep_range_max": 15,
        "progression_rate": 0.015,
        "aliases": ["pec deck", "pec deck fly", "machine chest fly", "butterfly machine"],
    },
    "push_up": {
        "display_name": "Push Up",
        "exercise_type": "bodyweight",
        "muscle_group": "Chest",
        "equipment": "Bodyweight",
        "rep_range_min": 8,
        "rep_range_max": 20,
        "progression_rate": 0.0,
        "aliases": ["push up", "pushup", "push-up", "push ups", "pushups"],
    },
    "chest_dip": {
        "display_name": "Chest Dip",
        "exercise_type": "bodyweight",
        "muscle_group": "Chest",
        "equipment": "Bodyweight",
        "rep_range_min": 6,
        "rep_range_max": 15,
        "progression_rate": 0.0,
        "aliases": ["chest dip", "dip", "dips", "parallel bar dip"],
    },
    "close_grip_bench_press": {
        "display_name": "Close-Grip Bench Press",
        "exercise_type": "compound",
        "muscle_group": "Chest",
        "equipment": "Barbell",
        "rep_range_min": 6,
        "rep_range_max": 12,
        "progression_rate": 0.025,
        "aliases": [
            "close-grip bench press", "close grip bench press",
            "cgbp", "close grip bench",
        ],
    },
    "smith_machine_bench_press": {
        "display_name": "Smith Machine Bench Press",
        "exercise_type": "compound",
        "muscle_group": "Chest",
        "equipment": "Machine",
        "rep_range_min": 6,
        "rep_range_max": 12,
        "progression_rate": 0.025,
        "aliases": ["smith machine bench press", "smith bench", "smith machine bench"],
    },

    # ── Back ─────────────────────────────────────────────────────────────────
    "deadlift": {
        "display_name": "Deadlift",
        "exercise_type": "compound",
        "muscle_group": "Back",
        "equipment": "Barbell",
        "rep_range_min": 3,
        "rep_range_max": 8,
        "progression_rate": 0.05,
        "aliases": [
            "deadlift", "conventional deadlift", "barbell deadlift",
            "bb deadlift", "dl",
        ],
    },
    "barbell_row": {
        "display_name": "Barbell Row",
        "exercise_type": "compound",
        "muscle_group": "Back",
        "equipment": "Barbell",
        "rep_range_min": 5,
        "rep_range_max": 12,
        "progression_rate": 0.025,
        "aliases": [
            "barbell row", "bent over row", "bent-over row", "bb row",
            "barbell bent over row", "barbell bent-over row",
        ],
    },
    "pendlay_row": {
        "display_name": "Pendlay Row",
        "exercise_type": "compound",
        "muscle_group": "Back",
        "equipment": "Barbell",
        "rep_range_min": 5,
        "rep_range_max": 10,
        "progression_rate": 0.025,
        "aliases": ["pendlay row"],
    },
    "t_bar_row": {
        "display_name": "T-Bar Row",
        "exercise_type": "compound",
        "muscle_group": "Back",
        "equipment": "Barbell",
        "rep_range_min": 6,
        "rep_range_max": 12,
        "progression_rate": 0.025,
        "aliases": ["t-bar row", "t bar row", "tbar row"],
    },
    "dumbbell_row": {
        "display_name": "Dumbbell Row",
        "exercise_type": "compound",
        "muscle_group": "Back",
        "equipment": "Dumbbell",
        "rep_range_min": 8,
        "rep_range_max": 15,
        "progression_rate": 0.025,
        "aliases": [
            "dumbbell row", "db row", "one arm row", "single arm dumbbell row",
            "one-arm dumbbell row",
        ],
    },
    "seated_cable_row": {
        "display_name": "Seated Cable Row",
        "exercise_type": "compound",
        "muscle_group": "Back",
        "equipment": "Cable",
        "rep_range_min": 8,
        "rep_range_max": 15,
        "progression_rate": 0.02,
        "aliases": ["seated cable row", "cable row", "low cable row"],
    },
    "lat_pulldown": {
        "display_name": "Lat Pulldown",
        "exercise_type": "compound",
        "muscle_group": "Back",
        "equipment": "Cable",
        "rep_range_min": 8,
        "rep_range_max": 15,
        "progression_rate": 0.02,
        "aliases": ["lat pulldown", "lat pull down", "cable pulldown"],
    },
    "straight_arm_pulldown": {
        "display_name": "Straight-Arm Pulldown",
        "exercise_type": "isolation",
        "muscle_group": "Back",
        "equipment": "Cable",
        "rep_range_min": 10,
        "rep_range_max": 15,
        "progression_rate": 0.015,
        "aliases": ["straight-arm pulldown", "straight arm pulldown", "cable pullover"],
    },
    "face_pull": {
        "display_name": "Face Pull",
        "exercise_type": "isolation",
        "muscle_group": "Back",
        "equipment": "Cable",
        "rep_range_min": 12,
        "rep_range_max": 20,
        "progression_rate": 0.015,
        "aliases": ["face pull", "cable face pull"],
    },
    "pull_up": {
        "display_name": "Pull Up",
        "exercise_type": "bodyweight",
        "muscle_group": "Back",
        "equipment": "Bodyweight",
        "rep_range_min": 5,
        "rep_range_max": 15,
        "progression_rate": 0.0,
        "aliases": ["pull up", "pullup", "pull-up", "pull ups", "pullups"],
    },
    "chin_up": {
        "display_name": "Chin Up",
        "exercise_type": "bodyweight",
        "muscle_group": "Back",
        "equipment": "Bodyweight",
        "rep_range_min": 5,
        "rep_range_max": 15,
        "progression_rate": 0.0,
        "aliases": ["chin up", "chinup", "chin-up", "chin ups", "chinups"],
    },
    "neutral_grip_pull_up": {
        "display_name": "Neutral Grip Pull Up",
        "exercise_type": "bodyweight",
        "muscle_group": "Back",
        "equipment": "Bodyweight",
        "rep_range_min": 5,
        "rep_range_max": 15,
        "progression_rate": 0.0,
        "aliases": ["neutral grip pull up", "neutral grip pullup", "hammer grip pull up"],
    },
    "hyperextension": {
        "display_name": "Hyperextension",
        "exercise_type": "isolation",
        "muscle_group": "Back",
        "equipment": "Machine",
        "rep_range_min": 10,
        "rep_range_max": 20,
        "progression_rate": 0.015,
        "aliases": ["hyperextension", "back extension", "roman chair"],
    },
    "good_morning": {
        "display_name": "Good Morning",
        "exercise_type": "compound",
        "muscle_group": "Back",
        "equipment": "Barbell",
        "rep_range_min": 8,
        "rep_range_max": 15,
        "progression_rate": 0.025,
        "aliases": ["good morning", "barbell good morning"],
    },
    "rack_pull": {
        "display_name": "Rack Pull",
        "exercise_type": "compound",
        "muscle_group": "Back",
        "equipment": "Barbell",
        "rep_range_min": 3,
        "rep_range_max": 8,
        "progression_rate": 0.05,
        "aliases": ["rack pull", "barbell rack pull", "partial deadlift"],
    },

    # ── Legs ─────────────────────────────────────────────────────────────────
    "barbell_squat": {
        "display_name": "Barbell Squat",
        "exercise_type": "compound",
        "muscle_group": "Legs",
        "equipment": "Barbell",
        "rep_range_min": 5,
        "rep_range_max": 10,
        "progression_rate": 0.05,
        "aliases": [
            "barbell squat", "squat", "back squat", "barbell back squat",
            "bb squat",
        ],
    },
    "front_squat": {
        "display_name": "Front Squat",
        "exercise_type": "compound",
        "muscle_group": "Legs",
        "equipment": "Barbell",
        "rep_range_min": 4,
        "rep_range_max": 8,
        "progression_rate": 0.04,
        "aliases": ["front squat", "barbell front squat"],
    },
    "hack_squat": {
        "display_name": "Hack Squat",
        "exercise_type": "compound",
        "muscle_group": "Legs",
        "equipment": "Machine",
        "rep_range_min": 8,
        "rep_range_max": 15,
        "progression_rate": 0.04,
        "aliases": ["hack squat", "machine hack squat"],
    },
    "leg_press": {
        "display_name": "Leg Press",
        "exercise_type": "compound",
        "muscle_group": "Legs",
        "equipment": "Machine",
        "rep_range_min": 8,
        "rep_range_max": 15,
        "progression_rate": 0.04,
        "aliases": ["leg press", "machine leg press"],
    },
    "romanian_deadlift": {
        "display_name": "Romanian Deadlift",
        "exercise_type": "compound",
        "muscle_group": "Legs",
        "equipment": "Barbell",
        "rep_range_min": 6,
        "rep_range_max": 12,
        "progression_rate": 0.04,
        "aliases": [
            "romanian deadlift", "rdl", "barbell rdl",
            "stiff leg deadlift",
        ],
    },
    "stiff_leg_deadlift": {
        "display_name": "Stiff-Leg Deadlift",
        "exercise_type": "compound",
        "muscle_group": "Legs",
        "equipment": "Barbell",
        "rep_range_min": 6,
        "rep_range_max": 12,
        "progression_rate": 0.04,
        "aliases": ["stiff-leg deadlift", "stiff leg deadlift", "sldl"],
    },
    "bulgarian_split_squat": {
        "display_name": "Bulgarian Split Squat",
        "exercise_type": "compound",
        "muscle_group": "Legs",
        "equipment": "Dumbbell",
        "rep_range_min": 8,
        "rep_range_max": 15,
        "progression_rate": 0.025,
        "aliases": [
            "bulgarian split squat", "split squat", "rear foot elevated split squat",
            "rfess",
        ],
    },
    "walking_lunge": {
        "display_name": "Walking Lunge",
        "exercise_type": "compound",
        "muscle_group": "Legs",
        "equipment": "Dumbbell",
        "rep_range_min": 10,
        "rep_range_max": 20,
        "progression_rate": 0.025,
        "aliases": ["walking lunge", "dumbbell lunge", "lunge"],
    },
    "goblet_squat": {
        "display_name": "Goblet Squat",
        "exercise_type": "compound",
        "muscle_group": "Legs",
        "equipment": "Dumbbell",
        "rep_range_min": 10,
        "rep_range_max": 20,
        "progression_rate": 0.025,
        "aliases": ["goblet squat", "dumbbell goblet squat"],
    },
    "leg_extension": {
        "display_name": "Leg Extension",
        "exercise_type": "isolation",
        "muscle_group": "Legs",
        "equipment": "Machine",
        "rep_range_min": 10,
        "rep_range_max": 20,
        "progression_rate": 0.015,
        "aliases": ["leg extension", "machine leg extension"],
    },
    "leg_curl": {
        "display_name": "Leg Curl",
        "exercise_type": "isolation",
        "muscle_group": "Legs",
        "equipment": "Machine",
        "rep_range_min": 10,
        "rep_range_max": 15,
        "progression_rate": 0.015,
        "aliases": ["leg curl", "hamstring curl", "lying leg curl", "seated leg curl"],
    },
    "standing_calf_raise": {
        "display_name": "Standing Calf Raise",
        "exercise_type": "isolation",
        "muscle_group": "Legs",
        "equipment": "Machine",
        "rep_range_min": 12,
        "rep_range_max": 20,
        "progression_rate": 0.015,
        "aliases": ["standing calf raise", "calf raise"],
    },
    "seated_calf_raise": {
        "display_name": "Seated Calf Raise",
        "exercise_type": "isolation",
        "muscle_group": "Legs",
        "equipment": "Machine",
        "rep_range_min": 12,
        "rep_range_max": 20,
        "progression_rate": 0.015,
        "aliases": ["seated calf raise"],
    },
    "hip_thrust": {
        "display_name": "Hip Thrust",
        "exercise_type": "compound",
        "muscle_group": "Legs",
        "equipment": "Barbell",
        "rep_range_min": 8,
        "rep_range_max": 15,
        "progression_rate": 0.04,
        "aliases": ["hip thrust", "barbell hip thrust", "glute thrust"],
    },
    "sumo_deadlift": {
        "display_name": "Sumo Deadlift",
        "exercise_type": "compound",
        "muscle_group": "Legs",
        "equipment": "Barbell",
        "rep_range_min": 3,
        "rep_range_max": 8,
        "progression_rate": 0.05,
        "aliases": ["sumo deadlift", "sumo dl", "wide stance deadlift"],
    },
    "step_up": {
        "display_name": "Step Up",
        "exercise_type": "compound",
        "muscle_group": "Legs",
        "equipment": "Dumbbell",
        "rep_range_min": 10,
        "rep_range_max": 20,
        "progression_rate": 0.025,
        "aliases": ["step up", "dumbbell step up", "box step up"],
    },

    # ── Shoulders ─────────────────────────────────────────────────────────────
    "overhead_press": {
        "display_name": "Overhead Press",
        "exercise_type": "compound",
        "muscle_group": "Shoulders",
        "equipment": "Barbell",
        "rep_range_min": 5,
        "rep_range_max": 10,
        "progression_rate": 0.025,
        "aliases": [
            "overhead press", "ohp", "barbell overhead press",
            "military press", "standing press", "barbell press",
        ],
    },
    "seated_dumbbell_press": {
        "display_name": "Seated Dumbbell Press",
        "exercise_type": "compound",
        "muscle_group": "Shoulders",
        "equipment": "Dumbbell",
        "rep_range_min": 8,
        "rep_range_max": 15,
        "progression_rate": 0.025,
        "aliases": [
            "seated dumbbell press", "db shoulder press", "dumbbell shoulder press",
            "seated db press",
        ],
    },
    "arnold_press": {
        "display_name": "Arnold Press",
        "exercise_type": "compound",
        "muscle_group": "Shoulders",
        "equipment": "Dumbbell",
        "rep_range_min": 8,
        "rep_range_max": 15,
        "progression_rate": 0.025,
        "aliases": ["arnold press"],
    },
    "lateral_raise": {
        "display_name": "Lateral Raise",
        "exercise_type": "isolation",
        "muscle_group": "Shoulders",
        "equipment": "Dumbbell",
        "rep_range_min": 12,
        "rep_range_max": 20,
        "progression_rate": 0.015,
        "aliases": ["lateral raise", "side lateral raise", "side raise", "lat raise"],
    },
    "cable_lateral_raise": {
        "display_name": "Cable Lateral Raise",
        "exercise_type": "isolation",
        "muscle_group": "Shoulders",
        "equipment": "Cable",
        "rep_range_min": 12,
        "rep_range_max": 20,
        "progression_rate": 0.015,
        "aliases": ["cable lateral raise", "cable side raise"],
    },
    "front_raise": {
        "display_name": "Front Raise",
        "exercise_type": "isolation",
        "muscle_group": "Shoulders",
        "equipment": "Dumbbell",
        "rep_range_min": 12,
        "rep_range_max": 20,
        "progression_rate": 0.015,
        "aliases": ["front raise", "dumbbell front raise"],
    },
    "rear_delt_fly": {
        "display_name": "Rear Delt Fly",
        "exercise_type": "isolation",
        "muscle_group": "Shoulders",
        "equipment": "Dumbbell",
        "rep_range_min": 12,
        "rep_range_max": 20,
        "progression_rate": 0.015,
        "aliases": [
            "rear delt fly", "reverse fly", "bent over rear delt fly",
            "rear fly",
        ],
    },
    "upright_row": {
        "display_name": "Upright Row",
        "exercise_type": "compound",
        "muscle_group": "Shoulders",
        "equipment": "Barbell",
        "rep_range_min": 8,
        "rep_range_max": 15,
        "progression_rate": 0.025,
        "aliases": ["upright row", "barbell upright row"],
    },
    "barbell_shrug": {
        "display_name": "Barbell Shrug",
        "exercise_type": "isolation",
        "muscle_group": "Shoulders",
        "equipment": "Barbell",
        "rep_range_min": 10,
        "rep_range_max": 15,
        "progression_rate": 0.025,
        "aliases": ["barbell shrug", "bb shrug", "shrug"],
    },
    "dumbbell_shrug": {
        "display_name": "Dumbbell Shrug",
        "exercise_type": "isolation",
        "muscle_group": "Shoulders",
        "equipment": "Dumbbell",
        "rep_range_min": 10,
        "rep_range_max": 15,
        "progression_rate": 0.025,
        "aliases": ["dumbbell shrug", "db shrug"],
    },
    "machine_shoulder_press": {
        "display_name": "Machine Shoulder Press",
        "exercise_type": "compound",
        "muscle_group": "Shoulders",
        "equipment": "Machine",
        "rep_range_min": 8,
        "rep_range_max": 15,
        "progression_rate": 0.025,
        "aliases": ["machine shoulder press", "hammer strength shoulder press"],
    },

    # ── Biceps ────────────────────────────────────────────────────────────────
    "barbell_curl": {
        "display_name": "Barbell Curl",
        "exercise_type": "isolation",
        "muscle_group": "Biceps",
        "equipment": "Barbell",
        "rep_range_min": 8,
        "rep_range_max": 15,
        "progression_rate": 0.015,
        "aliases": ["barbell curl", "bb curl", "straight bar curl"],
    },
    "dumbbell_curl": {
        "display_name": "Dumbbell Curl",
        "exercise_type": "isolation",
        "muscle_group": "Biceps",
        "equipment": "Dumbbell",
        "rep_range_min": 8,
        "rep_range_max": 15,
        "progression_rate": 0.015,
        "aliases": ["dumbbell curl", "db curl", "alternating curl"],
    },
    "hammer_curl": {
        "display_name": "Hammer Curl",
        "exercise_type": "isolation",
        "muscle_group": "Biceps",
        "equipment": "Dumbbell",
        "rep_range_min": 8,
        "rep_range_max": 15,
        "progression_rate": 0.015,
        "aliases": ["hammer curl", "neutral grip curl"],
    },
    "incline_dumbbell_curl": {
        "display_name": "Incline Dumbbell Curl",
        "exercise_type": "isolation",
        "muscle_group": "Biceps",
        "equipment": "Dumbbell",
        "rep_range_min": 8,
        "rep_range_max": 15,
        "progression_rate": 0.015,
        "aliases": ["incline dumbbell curl", "incline db curl"],
    },
    "preacher_curl": {
        "display_name": "Preacher Curl",
        "exercise_type": "isolation",
        "muscle_group": "Biceps",
        "equipment": "Barbell",
        "rep_range_min": 8,
        "rep_range_max": 15,
        "progression_rate": 0.015,
        "aliases": ["preacher curl", "ez bar preacher curl"],
    },
    "cable_curl": {
        "display_name": "Cable Curl",
        "exercise_type": "isolation",
        "muscle_group": "Biceps",
        "equipment": "Cable",
        "rep_range_min": 10,
        "rep_range_max": 15,
        "progression_rate": 0.015,
        "aliases": ["cable curl", "cable bicep curl"],
    },
    "concentration_curl": {
        "display_name": "Concentration Curl",
        "exercise_type": "isolation",
        "muscle_group": "Biceps",
        "equipment": "Dumbbell",
        "rep_range_min": 10,
        "rep_range_max": 15,
        "progression_rate": 0.015,
        "aliases": ["concentration curl"],
    },
    "spider_curl": {
        "display_name": "Spider Curl",
        "exercise_type": "isolation",
        "muscle_group": "Biceps",
        "equipment": "Dumbbell",
        "rep_range_min": 10,
        "rep_range_max": 15,
        "progression_rate": 0.015,
        "aliases": ["spider curl"],
    },
    "ez_bar_curl": {
        "display_name": "EZ-Bar Curl",
        "exercise_type": "isolation",
        "muscle_group": "Biceps",
        "equipment": "Barbell",
        "rep_range_min": 8,
        "rep_range_max": 15,
        "progression_rate": 0.015,
        "aliases": ["ez-bar curl", "ez bar curl", "ez curl"],
    },

    # ── Triceps ───────────────────────────────────────────────────────────────
    "triceps_pushdown": {
        "display_name": "Triceps Pushdown",
        "exercise_type": "isolation",
        "muscle_group": "Triceps",
        "equipment": "Cable",
        "rep_range_min": 10,
        "rep_range_max": 15,
        "progression_rate": 0.015,
        "aliases": [
            "triceps pushdown", "tricep pushdown", "cable pushdown",
            "triceps press down", "rope pushdown",
        ],
    },
    "skull_crusher": {
        "display_name": "Skull Crusher",
        "exercise_type": "isolation",
        "muscle_group": "Triceps",
        "equipment": "Barbell",
        "rep_range_min": 8,
        "rep_range_max": 15,
        "progression_rate": 0.015,
        "aliases": [
            "skull crusher", "skullcrusher", "lying tricep extension",
            "ez bar skull crusher",
        ],
    },
    "overhead_triceps_extension": {
        "display_name": "Overhead Triceps Extension",
        "exercise_type": "isolation",
        "muscle_group": "Triceps",
        "equipment": "Dumbbell",
        "rep_range_min": 10,
        "rep_range_max": 15,
        "progression_rate": 0.015,
        "aliases": [
            "overhead triceps extension", "overhead tricep extension",
            "dumbbell overhead extension",
        ],
    },
    "triceps_dip": {
        "display_name": "Triceps Dip",
        "exercise_type": "bodyweight",
        "muscle_group": "Triceps",
        "equipment": "Bodyweight",
        "rep_range_min": 8,
        "rep_range_max": 20,
        "progression_rate": 0.0,
        "aliases": ["triceps dip", "tricep dip", "bench dip"],
    },
    "diamond_push_up": {
        "display_name": "Diamond Push Up",
        "exercise_type": "bodyweight",
        "muscle_group": "Triceps",
        "equipment": "Bodyweight",
        "rep_range_min": 8,
        "rep_range_max": 20,
        "progression_rate": 0.0,
        "aliases": ["diamond push up", "diamond pushup", "close push up"],
    },
    "cable_overhead_extension": {
        "display_name": "Cable Overhead Extension",
        "exercise_type": "isolation",
        "muscle_group": "Triceps",
        "equipment": "Cable",
        "rep_range_min": 10,
        "rep_range_max": 15,
        "progression_rate": 0.015,
        "aliases": ["cable overhead extension", "cable overhead tricep extension"],
    },
    "kickback": {
        "display_name": "Kickback",
        "exercise_type": "isolation",
        "muscle_group": "Triceps",
        "equipment": "Dumbbell",
        "rep_range_min": 10,
        "rep_range_max": 15,
        "progression_rate": 0.015,
        "aliases": ["kickback", "dumbbell kickback", "tricep kickback"],
    },
    "close_grip_pushdown": {
        "display_name": "Close-Grip Pushdown",
        "exercise_type": "isolation",
        "muscle_group": "Triceps",
        "equipment": "Cable",
        "rep_range_min": 10,
        "rep_range_max": 15,
        "progression_rate": 0.015,
        "aliases": ["close-grip pushdown", "close grip pushdown"],
    },

    # ── Core ──────────────────────────────────────────────────────────────────
    "plank": {
        "display_name": "Plank",
        "exercise_type": "bodyweight",
        "muscle_group": "Core",
        "equipment": "Bodyweight",
        "rep_range_min": 1,
        "rep_range_max": 5,
        "progression_rate": 0.0,
        "aliases": ["plank", "forearm plank"],
    },
    "side_plank": {
        "display_name": "Side Plank",
        "exercise_type": "bodyweight",
        "muscle_group": "Core",
        "equipment": "Bodyweight",
        "rep_range_min": 1,
        "rep_range_max": 5,
        "progression_rate": 0.0,
        "aliases": ["side plank"],
    },
    "crunch": {
        "display_name": "Crunch",
        "exercise_type": "bodyweight",
        "muscle_group": "Core",
        "equipment": "Bodyweight",
        "rep_range_min": 15,
        "rep_range_max": 30,
        "progression_rate": 0.0,
        "aliases": ["crunch", "crunches", "abdominal crunch"],
    },
    "decline_crunch": {
        "display_name": "Decline Crunch",
        "exercise_type": "bodyweight",
        "muscle_group": "Core",
        "equipment": "Bodyweight",
        "rep_range_min": 15,
        "rep_range_max": 25,
        "progression_rate": 0.0,
        "aliases": ["decline crunch", "decline sit up"],
    },
    "hanging_leg_raise": {
        "display_name": "Hanging Leg Raise",
        "exercise_type": "bodyweight",
        "muscle_group": "Core",
        "equipment": "Bodyweight",
        "rep_range_min": 10,
        "rep_range_max": 20,
        "progression_rate": 0.0,
        "aliases": ["hanging leg raise", "hanging knee raise"],
    },
    "cable_crunch": {
        "display_name": "Cable Crunch",
        "exercise_type": "isolation",
        "muscle_group": "Core",
        "equipment": "Cable",
        "rep_range_min": 12,
        "rep_range_max": 20,
        "progression_rate": 0.015,
        "aliases": ["cable crunch", "kneeling cable crunch"],
    },
    "ab_rollout": {
        "display_name": "Ab Rollout",
        "exercise_type": "bodyweight",
        "muscle_group": "Core",
        "equipment": "Other",
        "rep_range_min": 8,
        "rep_range_max": 15,
        "progression_rate": 0.0,
        "aliases": ["ab rollout", "ab wheel rollout", "ab wheel roll out"],
    },
    "russian_twist": {
        "display_name": "Russian Twist",
        "exercise_type": "bodyweight",
        "muscle_group": "Core",
        "equipment": "Bodyweight",
        "rep_range_min": 15,
        "rep_range_max": 30,
        "progression_rate": 0.0,
        "aliases": ["russian twist"],
    },
    "mountain_climber": {
        "display_name": "Mountain Climber",
        "exercise_type": "bodyweight",
        "muscle_group": "Core",
        "equipment": "Bodyweight",
        "rep_range_min": 15,
        "rep_range_max": 30,
        "progression_rate": 0.0,
        "aliases": ["mountain climber", "mountain climbers"],
    },
    "bicycle_crunch": {
        "display_name": "Bicycle Crunch",
        "exercise_type": "bodyweight",
        "muscle_group": "Core",
        "equipment": "Bodyweight",
        "rep_range_min": 15,
        "rep_range_max": 30,
        "progression_rate": 0.0,
        "aliases": ["bicycle crunch", "bicycle crunches", "bike crunch"],
    },
    "dragon_flag": {
        "display_name": "Dragon Flag",
        "exercise_type": "bodyweight",
        "muscle_group": "Core",
        "equipment": "Bodyweight",
        "rep_range_min": 5,
        "rep_range_max": 12,
        "progression_rate": 0.0,
        "aliases": ["dragon flag"],
    },

    # ── Full Body ─────────────────────────────────────────────────────────────
    "power_clean": {
        "display_name": "Power Clean",
        "exercise_type": "compound",
        "muscle_group": "Full Body",
        "equipment": "Barbell",
        "rep_range_min": 3,
        "rep_range_max": 6,
        "progression_rate": 0.05,
        "aliases": ["power clean"],
    },
    "barbell_clean": {
        "display_name": "Barbell Clean",
        "exercise_type": "compound",
        "muscle_group": "Full Body",
        "equipment": "Barbell",
        "rep_range_min": 3,
        "rep_range_max": 6,
        "progression_rate": 0.05,
        "aliases": ["barbell clean", "clean"],
    },
    "thruster": {
        "display_name": "Thruster",
        "exercise_type": "compound",
        "muscle_group": "Full Body",
        "equipment": "Barbell",
        "rep_range_min": 5,
        "rep_range_max": 10,
        "progression_rate": 0.04,
        "aliases": ["thruster", "barbell thruster"],
    },
    "kettlebell_swing": {
        "display_name": "Kettlebell Swing",
        "exercise_type": "compound",
        "muscle_group": "Full Body",
        "equipment": "Other",
        "rep_range_min": 10,
        "rep_range_max": 20,
        "progression_rate": 0.025,
        "aliases": ["kettlebell swing", "kb swing"],
    },
    "turkish_get_up": {
        "display_name": "Turkish Get Up",
        "exercise_type": "compound",
        "muscle_group": "Full Body",
        "equipment": "Other",
        "rep_range_min": 3,
        "rep_range_max": 6,
        "progression_rate": 0.025,
        "aliases": ["turkish get up", "tgu"],
    },
    "burpee": {
        "display_name": "Burpee",
        "exercise_type": "bodyweight",
        "muscle_group": "Full Body",
        "equipment": "Bodyweight",
        "rep_range_min": 10,
        "rep_range_max": 20,
        "progression_rate": 0.0,
        "aliases": ["burpee", "burpees"],
    },
    "clean_and_press": {
        "display_name": "Clean and Press",
        "exercise_type": "compound",
        "muscle_group": "Full Body",
        "equipment": "Barbell",
        "rep_range_min": 3,
        "rep_range_max": 6,
        "progression_rate": 0.04,
        "aliases": ["clean and press", "clean & press"],
    },

    # ── Cardio ────────────────────────────────────────────────────────────────
    "treadmill_run": {
        "display_name": "Treadmill Run",
        "exercise_type": "bodyweight",
        "muscle_group": "Cardio",
        "equipment": "Machine",
        "rep_range_min": 1,
        "rep_range_max": 1,
        "progression_rate": 0.0,
        "aliases": ["treadmill run", "treadmill"],
    },
    "stationary_bike": {
        "display_name": "Stationary Bike",
        "exercise_type": "bodyweight",
        "muscle_group": "Cardio",
        "equipment": "Machine",
        "rep_range_min": 1,
        "rep_range_max": 1,
        "progression_rate": 0.0,
        "aliases": ["stationary bike", "bike"],
    },
    "rowing_machine": {
        "display_name": "Rowing Machine",
        "exercise_type": "bodyweight",
        "muscle_group": "Cardio",
        "equipment": "Machine",
        "rep_range_min": 1,
        "rep_range_max": 1,
        "progression_rate": 0.0,
        "aliases": ["rowing machine", "rower", "erg"],
    },
    "stair_climber": {
        "display_name": "Stair Climber",
        "exercise_type": "bodyweight",
        "muscle_group": "Cardio",
        "equipment": "Machine",
        "rep_range_min": 1,
        "rep_range_max": 1,
        "progression_rate": 0.0,
        "aliases": ["stair climber", "stepmill"],
    },
    "elliptical": {
        "display_name": "Elliptical",
        "exercise_type": "bodyweight",
        "muscle_group": "Cardio",
        "equipment": "Machine",
        "rep_range_min": 1,
        "rep_range_max": 1,
        "progression_rate": 0.0,
        "aliases": ["elliptical", "cross trainer"],
    },
    "jump_rope": {
        "display_name": "Jump Rope",
        "exercise_type": "bodyweight",
        "muscle_group": "Cardio",
        "equipment": "Other",
        "rep_range_min": 1,
        "rep_range_max": 1,
        "progression_rate": 0.0,
        "aliases": ["jump rope", "skipping rope", "skip rope"],
    },
    "assault_bike": {
        "display_name": "Assault Bike",
        "exercise_type": "bodyweight",
        "muscle_group": "Cardio",
        "equipment": "Machine",
        "rep_range_min": 1,
        "rep_range_max": 1,
        "progression_rate": 0.0,
        "aliases": ["assault bike", "air bike", "echo bike"],
    },
}

# ---------------------------------------------------------------------------
# Compile alias → canonical_name reverse lookup at import time
# ---------------------------------------------------------------------------

ALIAS_TO_CANONICAL: dict[str, str] = {}
for _canonical, _data in CANONICAL_EXERCISES.items():
    # Include the display_name itself as an alias (lowercased)
    _aliases = [_data["display_name"].lower()] + [a.lower() for a in _data["aliases"]]
    for _alias in _aliases:
        ALIAS_TO_CANONICAL[_alias] = _canonical


# ---------------------------------------------------------------------------
# Public helpers
# ---------------------------------------------------------------------------

def normalize_exercise_name(raw: str) -> Optional[str]:
    """
    Map a user-supplied exercise name to its canonical_name.

    Strips whitespace, lowercases, then looks up in ALIAS_TO_CANONICAL.
    Returns the canonical_name string if a match is found, else None.
    """
    key = raw.strip().lower()
    return ALIAS_TO_CANONICAL.get(key)


def get_exercise_metadata(canonical_name: str) -> Optional[dict]:
    """
    Return the full metadata dict for a canonical exercise, or None if not found.
    """
    return CANONICAL_EXERCISES.get(canonical_name)
